### PR TITLE
prometheus: add size of metrics store

### PR DESCRIPTION
**Pull request by jan--f**
Signed-off-by: Jan Fajerski <jfajerski@suse.com>

### CODE REVIEW

**Review by denisok — COMMENTED** [review]
it doesn't looks to address https://github.com/SUSE/supportutils-plugin-ses/issues/11
1st Martin wants human readable format.
2nd looks like @Martin-Weiss wants some detailed report on metrics structure.. so maybe just remove -s ? and add something like du -h --max-depth=1

**Comment by jan--f** [comment]
adding -h is giving us less information, but its small enough...why not both?

**Comment by jan--f** [comment]
> so maybe just remove -s

I'm not sure what info can be gleaned from the content of the metrics dir. Looks like this:
```
du -sh /var/lib/prometheus/metrics/*
4.0M	/var/lib/prometheus/metrics/00
5.5M	/var/lib/prometheus/metrics/01
7.7M	/var/lib/prometheus/metrics/02
8.4M	/var/lib/prometheus/metrics/03
2.9M	/var/lib/prometheus/metrics/04
3.3M	/var/lib/prometheus/metrics/05
5.0M	/var/lib/prometheus/metrics/06
4.5M	/var/lib/prometheus/metrics/07
4.1M	/var/lib/prometheus/metrics/08
4.4M	/var/lib/prometheus/metrics/09
12M	/var/lib/prometheus/metrics/0a
2.2M	/var/lib/prometheus/metrics/0b
3.5M	/var/lib/prometheus/metrics/0c
3.6M	/var/lib/prometheus/metrics/0d
5.6M	/var/lib/prometheus/metrics/0e
3.0M	/var/lib/prometheus/metrics/0f
5.9M	/var/lib/prometheus/metrics/10
3.1M	/var/lib/prometheus/metrics/11
7.6M	/var/lib/prometheus/metrics/12
4.1M	/var/lib/prometheus/metrics/13
2.1M	/var/lib/prometheus/metrics/14
3.3M	/var/lib/prometheus/metrics/15
4.4M	/var/lib/prometheus/metrics/16
3.6M	/var/lib/prometheus/metrics/17
2.8M	/var/lib/prometheus/metrics/18
3.2M	/var/lib/prometheus/metrics/19
...
```

**Comment by denisok** [comment]
I see, makes sense. I don't know what Martin men by "Maybe a find on this directory or a sub-dir ls with all details?"

**Review by denisok — APPROVED** [review]

**Comment by Martin-Weiss** [comment]
> 
> 
> I see, makes sense. I don't know what Martin men by "Maybe a find on this directory or a sub-dir ls with all details?"

Basically I have no idea about the metrics but I have the fear that the number of files (inodes) AND then size of the metrics might cause challenges. So far I just had the "out of disk space" situation - but "out of available inodes" could also be a challenge.

The major reason for this request was just because engineering asked for the information about existing deployments and I hope engineering can get this when supportconfig gathers them in the future.
(number of files, size of /var/lib/prometheus/metrics - and what else might required..)

**Review by Martin-Weiss — CHANGES_REQUESTED** [review]
How many direcories do we expect, here? Would it be useful for engineering in case we do a du -sh /var/lib/prometheus/metrics and du -s /var/lib/prometheus/metrics/* ? Maybe also a find /var/lib/prometheus/metrics|wc -l or similar?

**Comment by jan--f** [comment]
So far we treat the prometheus time series database as a black box. The structure of the metric store right now is for all intends and purposes meaningless to me. The internal format os also going to change in the next release.

Being a modern TSDB implementation I assume prometheus keeps reasonable bounds on things like number of files or directory tree depth. So unless there is a valid concern in regards to inodes (past incidents?) I'd like to skip it.

**Comment by Martin-Weiss** [comment]
>. So unless there is a valid concern in regards to inodes (past incidents?) I'd like to skip it.

As I have no idea how many inodes prometheus is going to use and if that is a problem at all I leave that in your hands. Just want to make sure to lock at and solve "possible problems" pro-active and before they hit the customers implementations instead of being "reactive" by looking at "past incidents" ;-).

Basically the root cause of this issue is the question "how much space and inodes" does a customer need to plan for the filesystem at /var/lib/prometheus/metrics. (customer was running out of available disk space because we are missing that information at the moment).
If that info could be known based on the product design and implementation - we would not even need that info reactive in the supportconfig.

**Comment by jan--f** [comment]
@Martin-Weiss lets go ahead with this. I don't anticipate any problems with inodes.

**Comment by Martin-Weiss** [comment]
> 
> 
> @Martin-Weiss lets go ahead with this. I don't anticipate any problems with inodes.

Sure - thanks!

P.S. next step is to find a way to extract this info from all supportconfigs to engineering so that engineering can come up with detailed requirements for the estimated disk space usage of the prometheus metrics..

**Pull request merged**
